### PR TITLE
Addressing stderr addition to output per issue #2

### PR DESCRIPTION
**Pull request by bnovotny**
Added stderr, line 131 as discussed in intern lecture series.

### CODE REVIEW

**Comment by pegeler** [comment]
Hi @brenkiz 

Thanks for the PR! 

This looks good, but the order in which list elements occur in the proposed solution differs from the `stats::t.test()` output. As you can see from the output below, `stderr` is sandwiched between `null.value` and `alternative`. Could you alter the PR to better reflect this?

```r
> str(t.test(1:10, y = c(7:20))) # From `t.test` Examples section
List of 10
 $ statistic  : Named num -5.43
  ..- attr(*, "names")= chr "t"
 $ parameter  : Named num 22
  ..- attr(*, "names")= chr "df"
 $ p.value    : num 1.86e-05
 $ conf.int   : num [1:2] -11.05 -4.95
  ..- attr(*, "conf.level")= num 0.95
 $ estimate   : Named num [1:2] 5.5 13.5
  ..- attr(*, "names")= chr [1:2] "mean of x" "mean of y"
 $ null.value : Named num 0
  ..- attr(*, "names")= chr "difference in means"
 $ stderr     : num 1.47
 $ alternative: chr "two.sided"
 $ method     : chr "Welch Two Sample t-test"
 $ data.name  : chr "1:10 and c(7:20)"
 - attr(*, "class")= chr "htest"
```

It might also be a good idea to change the DESCRIPTION file so that it depends R (>= 3.6.0) so that users with previous versions of R still have consistent output. Or it might be cool to modify the output based on the R version.

One final thing, please increment the version number as well.

Thanks!

**Comment by bnovotny** [comment]
Hi @pegeler,

I have updated the version number and added myself as a contributor in the DESCRIPTION file, as well as fixed the output order and compatibility with version 3.6.0 in the script.

Thanks very much!

**Review by pegeler — APPROVED** [review]
Looks good!

**Review by kampfsca — APPROVED** [review]
Nice  Work

**Pull request merged**
